# -*- coding: utf-8 -*-
"""Classrooms_Scheduling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uIgMoZHWKBJA1iRfE9epMKFrK3Vdj1Vb
"""

import pandas as pd
import re

df = pd.read_excel(r'/content/sample_data/BaruchSchedule-2022-10-18.xlsx')

newdf = pd.DataFrame(columns = ['Subject','Catalog','Section','Total'])

for index in df.index:
  d = df['Day'][index]
  days = re.findall('[A-Z][^A-Z]*', d)

  for x in days:
    newdf.loc[len(newdf.index)]= [df['Room'][index], x, df['Start'][index], df['End'][index]]

newdf["Semester"] = 'Spring'
newdf["Year"] = 2023
newdf.to_excel("Book1.xlsx")