# -*- coding: utf-8 -*-
"""OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12KeW6Cgwuai1Eg4re0MaodhcqE9qeKPi
"""

pip install easyocr

pip install xlsxwriter

import easyocr
import xlsxwriter

path = '/content/sample_data/Image 6.png'
reader = easyocr.Reader(['en'])
result = reader.readtext(path,detail=0)
#result

workbook = xlsxwriter.Workbook('/content/sample_data/Book1.xlsx')

worksheet = workbook.add_worksheet()

flag = 0
row = 0
column = 0

for i in result:

  if flag == 1:
    worksheet.write(row,column,i)
    column += 1
  elif flag == 2:
    worksheet.write(row,column,i)
    column += 1
  elif flag == 3:
    worksheet.write(row,column,i)
    column += 1
  elif flag == 4:
    worksheet.write(row,column,i)
    column += 1
  elif flag == 5:
    worksheet.write(row,column,i)
    column += 1
  elif flag == 6:
    worksheet.write(row,column,i)
    row += 1
    column = 0
    

  if i == "PROGRAM CODE": #flag 1
    flag = 1
  elif i == "PROGRAM TITLE": #flag 2
    flag = 2
  elif i == "AWARD": #flag 3
    flag = 3
  elif i == "INST . NAME / CITY:": #flag 4
    flag = 4
  elif i == "INST . NAME / CITY :": #flag 4
    flag = 4
  elif i == "INST . NAME /CITY :": #flag 4
    flag = 4 
  elif i == "NAME / CITY:": #flag 4
    flag = 4
  elif i == "INST . NAME/ CITY :": #flag 4
    flag = 4
  elif i == "HEGIS": #flag 5
    flag = 5    
  elif i == "CODE": #flag 6
    flag = 6
  elif i == "UNIT CODE": #flag 6
    flag = 6
  else:
    flag = 0


workbook.close()